In [ ]:
#Data Types in R - 
# Character
# Numeric
# Integer
# Complex
# Logical – True/False

In [5]:
x <- "R Programming Refresher"
class(x)
y <- 3.14
class(y)
z <- 69L
class(z)
c <- 5 +69i
class(c)
l <- TRUE
class(l)

[1] "character"

[1] "numeric"

[1] "integer"

[1] "complex"

[1] "logical"

In [34]:
#Each object has specific attributes like:
# names
# dim
# class
# length
# others attributes defined by the user

myList <- list(age=c(10,21,39),weight=c(30,50,65))
names(myList)
length(myList)

[1] "age"    "weight"

[1] 2

In [15]:
#vector
vec <- c("This","Is", "A", "Character","Vector")
vec
class(vec)
#vectors need to be of the same class

[1] "This"      "Is"        "A"         "Character" "Vector"

[1] "character"

In [17]:
#indexing  in  R  starts from 1 and not 0.
f <- vector(mode="logical",length = 5)
f
f[1] = TRUE
f

[1] FALSE FALSE FALSE FALSE FALSE

[1]  TRUE FALSE FALSE FALSE FALSE

In [22]:
#Lists - can be collection of different classes
L <- list("Hello Peter", 69L , 69.69, TRUE)
L
class(L[[2]]) #accessing the 2nd element

[[1]]
[1] "Hello Peter"

[[2]]
[1] 69

[[3]]
[1] 69.69

[[4]]
[1] TRUE

[1] "integer"

In [31]:
#Matrix - collection of multiple vectors
#----------There are many ways to declare a matrix
#------1.create a vector and then set dimensions with the dim function

mat <- c(1,2,3,4)
dim(mat)<- c(2,2)
mat

#------2.create a matrix by using the matrix function
rollNumber <- c(1,2,3,4,5,6)
mat2 <- matrix(rollNumber, nrow=2 , ncol=3 , byrow=TRUE) #by using byrow=true
mat2
mat2 <- matrix(rollNumber, nrow=2 , ncol=3 ) #with default byrow = false
mat2

#------3. merging existing vectors either by rows using the function rbind or by columns using the cbind function
v1 <- c(20,45,47)
v2 <- c(60,54,100)
#By Rows---
rbind(v1,v2)
#By Columns---
cbind(v1,v2)

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2] [,3]
v1 20   45    47 
v2 60   54   100

v1 v2 
[1,] 20  60
[2,] 45  54
[3,] 47 100

In [33]:
#factors: an  easy  way  to  represent  and  manage  nominal  data
factor(c("Yes","No","Yes","No"))
fac <- factor(c("Yes","No","Yes","No"),levels=c("Yes"))
fac

[1] Yes No  Yes No 
Levels: No Yes

[1] Yes  <NA> Yes  <NA>
Levels: Yes

In [38]:
#Missing Values
x <- NA
is.na(x)
y <- 0/0
y
is.nan(y)

[1] TRUE

[1] NaN

[1] TRUE

In [44]:
# Data Frames - store data in a table format, can have different type of data in each column. 
x <- c("Tarantino", "Scorcese", "Nolan")
y <- c(9, 25, 8)
z <- c(TRUE, TRUE, FALSE)

dataFrame = data.frame(directorName = x , noOfMovies = y, Oscars = z)
dataFrame
dataFrame[1,] #first row
dataFrame[,1] #first col
dataFrame$Oscars #accessing using column name

directorName noOfMovies Oscars
1 Tarantino     9          TRUE 
2 Scorcese     25          TRUE 
3 Nolan         8         FALSE

directorName noOfMovies Oscars
1 Tarantino    9          TRUE

[1] Tarantino Scorcese  Nolan    
Levels: Nolan Scorcese Tarantino

[1]  TRUE  TRUE FALSE